Ft nags user until resolved #158174590
andela/hc-aces-kla pull request #10
Opened 2018-06-28 18:15 UTC by archbishop12

What does this PR do?
* Add continues alerts to the user if job remains unresolved
Description of Task to be completed?
Implementing the following changes to the files
* templates/front/my_checks.html
    * Add nag icon 
    * Add nag interval option for user
* front/views.py
    * Add nag interval logic for updating the value
* Api/management/sendalerts.py
    * Add logic to send alerts to user if job goes down until it goes up again.
* Front/tests/test_update_nag_interval.py
    * Testing update_nag_interval method.
* Api/tests/test_send_alerts_resolved.py
    * Testing it handles unresolved.
How should this be manually tested?
After cloning the repo, run the following commands
* python manage.py test

What are the relevant pivotal tracker stories?
#158174590
<img width="1381" alt="screen shot 2018-06-28 at 17 22 01" src="https://user-images.githubusercontent.com/39958516/42052667-18ddf082-7b18-11e8-80b2-93a1af6fabe6.png">

2018-06-29 05:59 UTC, EdwinKato commented
@archbishop12 remove the virtual_env files from the remote repo

2018-06-29 07:23 UTC, EdwinKato commented
@archbishop12 your build is failing. Some test is failing

2018-06-29 08:05 UTC, archbishop12 commented
Hi Edwin, the build is now passing.

2018-06-29 17:24 UTC, EdwinKato commented
@archbishop12 Resolve conflicts

2018-06-29 17:42 UTC, archbishop12 commented
Conflicts resolved

2018-07-02 08:15 UTC, EdwinKato requested changes

2018-07-02 08:15 UTC, EdwinKato commented on hc/api/management/commands/sendalerts.py
> +            print("false")
I'm guessing this was left out after debugging. If so remove it after

2018-07-02 08:15 UTC, EdwinKato commented on hc/settings.py
> +EMAIL_HOST_PASSWORD = 'hc@ce5kla'
Configure sensitive information such as the password in the local settings file or the environment. Committing it with your source code could expose a possible vulnerability

2018-07-02 10:13 UTC, archbishop12 commented
I have removed the email credentials and the print.

2018-07-02 15:13 UTC, EdwinKato commented
@archbishop12 resolve conflicts

2018-07-03 07:28 UTC, EdwinKato approved these changes

2018-07-03 07:29 UTC, merged