feature sms and voice integrations 158174594
andela/hc-aces-kla pull request #11
Opened 2018-06-29 06:45 UTC by magicmarie

What does this PR do?
Sets up healthchecks to be able to send out alerts concerning the cron jobs through SMS and voice. Right now, Healthchecks only sends alerts through email.

Description of Task to be completed?
The system is able to send out alerts through SMS and voice channels.

The files changed/created include:
Created:
add_twiliosms.html - Added UI for the page where the phone number is added
add_twiliovoice.html - Added UI for the page where the phone number is added

Edited
hc/api/transports.py - Added the SMS and voice models
hc/front/urls.py - Added the URL that redirects to the sms and voice configuration pages
hc/front/views.py - Added the function that loads the page where the number to sms is added
hc/templates/front/channels.html - Added sms and voice to the list of configurable channel options
hc/front/tests/test_add_channel.py - Added tests for sms and voice access

What are the relevant pivotal tracker stories?
[#158174594](https://www.pivotaltracker.com/n/projects/2177206)

2018-06-29 15:53 UTC, EdwinKato commented
@magicmarie @mutebironald resolve conflicts

2018-06-29 17:21 UTC, EdwinKato requested changes

2018-06-29 17:21 UTC, EdwinKato commented on hc/api/transports.py
> +auth_token = "f323d7a1411ef651daa54dacb4147dfb"
Store these credentials in an environment. It's not good to commit these with your source code

2018-06-29 17:21 UTC, EdwinKato commented on hc/api/transports.py
> +        message = client.messages.create(
This variable `message` is not used anywhere

2018-06-29 17:21 UTC, EdwinKato commented on hc/api/transports.py
> +client = Client(account_sid, auth_token)
`client` has 2 usages. Use OOP here. Consider putting it in the transport class

2018-06-29 17:21 UTC, EdwinKato commented on hc/front/tests/test_add_channel.py
> +        """ test sms intergration works"""
Rectify spelling of intergration

2018-07-02 13:49 UTC, EdwinKato requested changes

2018-07-02 13:49 UTC, EdwinKato commented on hc/api/transports.py
> +# TWILIO_AUTH_TOKEN = os.environ.get("TWILIO_AUTH_TOKEN")
Remove these commented out lines

2018-07-02 13:49 UTC, EdwinKato commented on hc/front/tests/test_add_channel.py
> +        url = "/integrations/add/"
Use reverse for `urls` always

2018-07-02 14:17 UTC, mutebironald commented on hc/front/tests/test_add_channel.py
> +        url = "/integrations/add/"
worked on this.

2018-07-02 15:12 UTC, EdwinKato approved these changes

2018-07-02 15:12 UTC, merged