Ch travis permit deployment of branches on andela/hc-aces-kla
andela/hc-aces-kla pull request #25
Opened 2018-07-12 18:29 UTC by matthewacha

## Status
**IN DEVELOPMENT**

## Migrations
NO

## Description
This PR give permission for the deployment across all branches on the repository

## Todos
- [ ] .travis.yml

## Deploy Notes
Notes regarding deployment the contained body of work.  These should note any
.travis.yml file runs deployment for all branches in the repo andela/hc-aces-kla.

## Steps to Test or Reproduce
Outline the steps to test or reproduce the PR here.

```sh
git pull 
git checkout ch-travis-permit-develop-deployment
```

## Impacted Areas in Application

* travis build
* heroku build

2018-07-12 21:04 UTC, EdwinKato requested changes

2018-07-12 21:04 UTC, EdwinKato commented on .travis.yml
> +    repo: andela/hc-aces-kla
Add the branch as-well (develop)

2018-07-13 06:39 UTC, matthewacha commented on .travis.yml
> +    repo: andela/hc-aces-kla
Done

2018-07-13 06:41 UTC, EdwinKato approved these changes

2018-07-13 06:42 UTC, merged