Ft test accounts #158174587
andela/hc-aces-kla pull request #4
Opened 2018-06-25 18:18 UTC by matthewacha

#### What does this PR do?
- Fixes unit tests in the directory hc/accounts/tests
- Adds new tests for untested components
 standards
#### Description of Task to be completed?
Implementing the following test cases
- test_check_token.py
  - test_redirects_already_logged_in
  - test_login_bad_token_redirects
- test_login.py
  - test_it_redirects_when_password_given
- test_profile.py
 - test_it_sends_set_password_link
   - Assert that the token is set
   - Assert that the email was sent and check email content
 - test_it_sends_report
   - Assert that the email was sent and check email content
 - test_it_adds_team_member
   - Assert the existence of the member emails
   - Assert that the email was sent and check email content
 - test_it_creates_and_revokes_api
 - test_it_updates_reports
-test_switch_team.py
 - test_it_switches
   - Assert the contents of r
 - test_it_checks_team_membership
   - Assert the expected error code
 - test_it_switches_to_own_team
   - Assert the expected response code
 - test_team_access_middleware.py
   - test_it_handles_missing_profile
     -Assert the new Profile objects count

#### How should this be manually tested?
After cloning the repo, run the following commands
- make
- python manage.py test
#### Any background context you want to provide?
This is necessary before any further code implementation is made to the code base
#### What are the relevant pivotal tracker stories?
[#158174587](https://www.pivotaltracker.com/n/projects/2177206)

2018-06-26 13:37 UTC, magicmarie commented
Nice one on the docstrings. The rest of us should pick a leaf

2018-06-26 16:01 UTC, EdwinKato requested changes

2018-06-26 16:01 UTC, EdwinKato commented on hc/accounts/tests/test_check_token.py
> +        self.assertRedirects(re, "/checks/")
Use reverse for these urls `reverse("hc-checks")`

2018-06-26 16:01 UTC, EdwinKato commented on hc/accounts/tests/test_check_token.py
> +        self.assertRedirects(response_bad_token,"/accounts/login/")
You can do without line 37. Leave a space `response_bad_token`

2018-06-27 17:07 UTC, EdwinKato commented
@matthewacha resolve conflicts

2018-06-29 05:54 UTC, EdwinKato approved these changes

2018-06-29 05:54 UTC, merged